import re

IT_MAPPING = {
    # =========================================================
    # COMPOSÉS / VARIANTES PRIORITAIRES
    # =========================================================
    "ci/cd": "intégration continue déploiement continu automatisation livraison logicielle",
    "ci cd": "intégration continue déploiement continu automatisation livraison logicielle",
    "ci pipeline": "pipeline intégration continue automatisation build tests",
    "cd pipeline": "pipeline déploiement continu automatisation livraison production",
    "gpu accel": "accélération matérielle processeur graphique calcul intensif",
    "bdd test": "développement piloté par le comportement tests automatisés comportement utilisateur",
    "eda archi": "architecture orientée événements systèmes distribués communication asynchrone",
    "eda arch": "architecture orientée événements systèmes distribués communication asynchrone",
    "event driven": "architecture orientée événements systèmes distribués communication asynchrone",
    "event-driven": "architecture orientée événements systèmes distribués communication asynchrone",
    "micro services": "microservices architecture distribuée découpage applicatif services indépendants",
    "micro-services": "microservices architecture distribuée découpage applicatif services indépendants",
    "full stack": "développement full stack front end back end développement complet",
    "front end": "front end interface utilisateur développement web client",
    "frontend": "front end interface utilisateur développement web client",
    "back end": "back end logique serveur développement applicatif",
    "backend": "back end logique serveur développement applicatif",
    "object oriented": "programmation orientée objet",
    "object-oriented": "programmation orientée objet",
    "oop dev": "programmation orientée objet conception logicielle classes héritage polymorphisme",
    "rest api": "api rest architecture web communication services",
    "restful api": "api rest architecture web communication services",
    "web api": "interface programmation applicative web communication services",
    "cloud native": "applications cloud natives architecture conteneurs microservices scalabilité",
    "server side": "logique serveur back end traitement côté serveur",
    "client side": "interface utilisateur front end traitement côté client",
    "infra as code": "infrastructure en tant que code automatisation infrastructure cloud déploiement",
    "data viz": "visualisation données analyse graphique tableaux de bord",
    "data visualization": "visualisation données analyse graphique tableaux de bord",
    "deep learning": "apprentissage profond réseaux de neurones",
    "machine learning": "apprentissage automatique",
    "natural language processing": "traitement du langage naturel",
    "computer vision": "vision par ordinateur",
    "business intelligence": "informatique décisionnelle analyse reporting aide à la décision tableaux de bord",
    "big data": "données massives traitement distribué stockage distribué analytique",
    "prompt eng": "ingénierie des prompts interaction modèles de langage",
    "prompt engineering": "ingénierie des prompts interaction modèles de langage",
    "gen ai": "intelligence artificielle générative modèles génératifs",
    "genai": "intelligence artificielle générative modèles génératifs",

    # =========================================================
    # IA / DATA SCIENCE / IA GÉNÉRATIVE
    # =========================================================
    "ai": "intelligence artificielle",
    "ia": "intelligence artificielle",
    "genai": "intelligence artificielle générative modèles génératifs",
    "agi": "intelligence artificielle générale",
    "ml": "apprentissage automatique",
    "dl": "apprentissage profond",
    "rl": "apprentissage par renforcement",
    "nlp": "traitement du langage naturel",
    "nlu": "compréhension du langage naturel",
    "nlg": "génération du langage naturel",
    "cv": "vision par ordinateur",
    "asr": "reconnaissance automatique de la parole",
    "stt": "transcription parole en texte reconnaissance vocale",
    "tts": "synthèse vocale",
    "llm": "modèle de langage de grande taille",
    "vlm": "modèle vision langage multimodal",
    "vla": "vision langage action robotique intelligence artificielle",
    "rag": "génération augmentée par récupération recherche contexte",
    "lora": "adaptation faible rang fine tuning modèles",
    "qlora": "adaptation faible rang quantifiée fine tuning modèles",
    "peft": "fine tuning efficace en paramètres adaptation modèles",
    "sft": "fine tuning supervisé entraînement supervisé modèles",
    "rlhf": "apprentissage par renforcement à partir préférences humaines",
    "dpo": "optimisation directe des préférences alignement modèles",
    "cot": "chaîne de raisonnement raisonnement étape par étape",
    "moe": "mélange d'experts architecture modèles",
    "vae": "autoencodeur variationnel génération de données",
    "gan": "réseau antagoniste génératif génération de données",
    "gmm": "modèle de mélange gaussien clustering probabiliste",
    "hmm": "modèle de Markov caché séquences temporelles",
    "knn": "plus proches voisins classification apprentissage automatique",
    "svm": "machines à vecteurs de support classification",
    "xai": "explicabilité intelligence artificielle interprétabilité modèles",
    "aio": "optimisation intelligence artificielle opérations automatisation",
    "mcp": "protocol de contexte modèle intégration outils agents",
    "aiops": "intelligence artificielle pour opérations informatiques supervision automatisation",

    # =========================================================
    # DATA / BI / ANALYSE / INGÉNIERIE DES DONNÉES
    # =========================================================
    "bi": "informatique décisionnelle analyse reporting aide à la décision tableaux de bord",
    "ba": "analyse métier business analysis besoins processus organisation",
    "eda": "analyse exploratoire des données statistiques visualisation",
    "dqm": "gestion qualité des données validation nettoyage données",
    "dq": "qualité des données validation nettoyage données",
    "mdm": "gestion des données de référence gouvernance données",
    "etl": "extraction transformation chargement intégration données pipeline données",
    "elt": "extraction chargement transformation intégration données pipeline données",
    "cdc": "capture des changements données synchronisation réplication",
    "olap": "analyse multidimensionnelle données décisionnelles",
    "oltp": "traitement transactionnel systèmes opérationnels",
    "dwh": "entrepôt de données stockage analytique données décisionnelles",
    "dw": "entrepôt de données stockage analytique données décisionnelles",
    "dm": "fouille de données analyse prédictive",
    "datamart": "magasin de données données décisionnelles orientées métier",
    "kpi": "indicateur clé de performance suivi performance",
    "roi": "retour sur investissement analyse financière",
    "sla": "accord niveau de service disponibilité performance",
    "slo": "objectif niveau de service disponibilité",
    "sli": "indicateur niveau de service mesure performance",
    "lakehouse": "architecture données combinant lac de données et entrepôt analytique",
    "dlh": "lac de données stockage brut données massives",
    "datalake": "lac de données stockage brut données massives",
    "data lake": "lac de données stockage brut données massives",
    "medallion": "architecture bronze silver gold transformation progressive données",
    "cdp": "plateforme de données client centralisation données client",
    "bpm": "gestion des processus métier analyse optimisation workflows",
    "mis": "système d'information de gestion reporting pilotage",
    "gis": "système d'information géographique cartographie données spatiales",

    # =========================================================
    # BASES DE DONNÉES
    # =========================================================
    "bdd": "base de données",
    "bd": "base de données",
    "db": "base de données",
    "sgbd": "système de gestion base de données",
    "dbms": "système gestion base de données",
    "rdbms": "base de données relationnelle",
    "nosql": "base de données non relationnelle",
    "sql db": "base de données relationnelle sql",
    "acid": "atomicité cohérence isolation durabilité transactions",
    "base": "théorème basically available soft state eventual consistency",
    "cap": "cohérence disponibilité tolérance partitionnement systèmes distribués",
    "crud": "création lecture mise à jour suppression données",
    "orm": "mapping objet relationnel accès base de données",
    "odm": "mapping objet document base de données documentaires",
    "er": "modèle entité relation modélisation base de données",
    "erd": "diagramme entité relation modélisation base de données",
    "pk": "clé primaire identifiant unique",
    "fk": "clé étrangère relation entre tables",
    "uuid": "identifiant universel unique",
    "uid": "identifiant unique",
    "shard": "partitionnement horizontal base de données distribuée",
    "sharding": "partitionnement horizontal base de données distribuée",
    "replica": "réplication base de données haute disponibilité",
    "replication": "réplication base de données haute disponibilité",
    "mvcc": "contrôle de concurrence multiversion transactions base de données",

    # =========================================================
    # ARCHITECTURE / DEV / CONCEPTION LOGICIELLE
    # =========================================================
    "api": "interface programmation applicative communication services intégration systèmes",
    "sdk": "kit développement logiciel bibliothèque outils développement",
    "cli": "interface en ligne de commande",
    "gui": "interface utilisateur graphique",
    "rest": "architecture rest api web communication services",
    "soap": "protocole services web échange messages xml",
    "graphql": "langage requête api flexible données",
    "grpc": "appel procédure distante haute performance communication services",
    "rpc": "appel procédure distante communication systèmes",
    "soa": "architecture orientée services intégration systèmes",
    "msa": "architecture microservices services indépendants distribués",
    "mvc": "modèle vue contrôleur architecture logicielle",
    "mvp": "modèle vue présentateur architecture logicielle",
    "mvvm": "modèle vue vue-modèle architecture logicielle",
    "hex": "architecture hexagonale conception logicielle",
    "clean arch": "architecture propre séparation responsabilités conception logicielle",
    "clean architecture": "architecture propre séparation responsabilités conception logicielle",
    "ddd": "conception orientée domaine métier",
    "cqrs": "séparation commandes requêtes architecture",
    "es": "event sourcing historique événements architecture",
    "dry": "ne pas se répéter réutilisation code",
    "kiss": "simplicité conception logicielle",
    "solid": "principes de conception orientée objet maintenabilité logiciel",
    "yagni": "ne pas implémenter l'inutile conception logicielle",
    "ioc": "inversion de contrôle architecture logicielle",
    "di": "injection de dépendances architecture logicielle",
    "aop": "programmation orientée aspects modularisation préoccupations transverses",

    # =========================================================
    # DEVOPS / SRE / AUTOMATISATION / PLATEFORME
    # =========================================================
    "ci": "intégration continue automatisation build tests",
    "cd": "déploiement continu automatisation livraison",
    "ct": "tests continus automatisation qualité logicielle",
    "devops": "développement opérations automatisation déploiement infrastructure fiabilité",
    "devsecops": "développement sécurité opérations automatisation déploiement",
    "gitops": "gestion opérations basée git automatisation déploiement infrastructure",
    "mlops": "industrialisation apprentissage automatique déploiement suivi modèles",
    "dataops": "automatisation pipelines données qualité gouvernance collaboration",
    "modelops": "gestion cycle de vie modèles déploiement supervision",
    "sre": "ingénierie fiabilité systèmes supervision disponibilité infrastructure",
    "iac": "infrastructure en tant que code automatisation infrastructure cloud déploiement",
    "cm": "gestion de configuration automatisation infrastructure",
    "rpa": "automatisation robotisée processus",
    "alM": "gestion cycle de vie applicatif développement qualité livraison",
    "alm": "gestion cycle de vie applicatif développement qualité livraison",
    "itil": "gestion services informatiques processus exploitation support",
    "itsm": "gestion des services informatiques support exploitation",
    "noc": "centre supervision réseau exploitation surveillance",
    "run": "exploitation production maintenance opérationnelle",
    "build": "conception développement construction solution",
    "finops": "gestion financière du cloud optimisation coûts cloud",
    "platform eng": "ingénierie plateforme outillage développeurs infrastructure self service",
    "platform engineering": "ingénierie plateforme outillage développeurs infrastructure self service",

    # =========================================================
    # SYSTÈMES / HARDWARE
    # =========================================================
    "vm": "machine virtuelle virtualisation",
    "vps": "serveur privé virtuel hébergement",
    "os": "système exploitation",
    "cpu": "processeur",
    "gpu": "processeur graphique calcul parallèle",
    "tpu": "accélérateur tensoriel apprentissage automatique",
    "npu": "unité de traitement neuronal intelligence artificielle",
    "ram": "mémoire vive",
    "rom": "mémoire morte",
    "ssd": "stockage rapide ssd",
    "nvme": "stockage nvme haute performance",
    "hdd": "disque dur stockage",
    "bios": "micrologiciel démarrage système",
    "uefi": "micrologiciel moderne démarrage système",
    "dma": "accès direct mémoire",
    "io": "entrées sorties système",
    "iops": "opérations entrées sorties par seconde performance stockage",
    "raid": "redondance stockage performance disponibilité",
    "san": "réseau de stockage",
    "nas": "stockage réseau partagé",
    "iscsi": "protocole stockage en réseau",
    "kvm": "virtualisation noyau machine virtuelle",
    "hyperv": "virtualisation machine virtuelle hyperviseur",
    "vmware": "virtualisation infrastructure serveurs",
    "vdi": "infrastructure de bureau virtuel",

    # =========================================================
    # UI / UX / WEB / MOBILE
    # =========================================================
    "ui": "interface utilisateur",
    "ux": "expérience utilisateur",
    "uiux": "interface utilisateur expérience utilisateur design",
    "uxui": "interface utilisateur expérience utilisateur design",
    "fe": "front end interface utilisateur",
    "be": "back end logique serveur",
    "fs": "full stack développement complet",
    "spa": "application monopage interface web dynamique",
    "mpa": "application web multipage",
    "pwa": "application web progressive expérience mobile hors ligne",
    "ssr": "rendu côté serveur performance web",
    "csr": "rendu côté client interface web",
    "dom": "modèle objet document interface web",
    "a11y": "accessibilité numérique interface utilisateur",
    "seo": "optimisation pour moteurs de recherche visibilité web",
    "wcag": "directives accessibilité contenu web",
    "hci": "interaction humain ordinateur ergonomie interfaces",
    "cx": "expérience client parcours utilisateur",

    # =========================================================
    # PROGRAMMATION / GÉNIE LOGICIEL
    # =========================================================
    "oop": "programmation orientée objet",
    "poo": "programmation orientée objet",
    "oo": "orienté objet programmation",
    "fp": "programmation fonctionnelle",
    "pp": "programmation procédurale",
    "dsa": "structures données algorithmes",
    "algo": "algorithmes résolution de problèmes",
    "dsl": "langage spécifique à un domaine",
    "jit": "compilation juste à temps optimisation exécution",
    "aot": "compilation anticipée optimisation exécution",
    "gc": "ramasse miettes gestion mémoire automatique",
    "vm lang": "langage exécuté sur machine virtuelle",
    "asm": "langage assembleur programmation bas niveau",

    # =========================================================
    # CLOUD / FOURNISSEURS / SERVICES
    # =========================================================
    "cloud": "informatique en nuage infrastructure services hébergement scalabilité",
    "public cloud": "cloud public infrastructure mutualisée services hébergés",
    "private cloud": "cloud privé infrastructure dédiée",
    "hybrid cloud": "cloud hybride infrastructure mixte",
    "multi cloud": "multi cloud plusieurs fournisseurs cloud",
    "saas": "logiciel service cloud",
    "paas": "plateforme service cloud",
    "iaas": "infrastructure service cloud",
    "faas": "fonction service cloud",
    "caas": "conteneurs en tant que service cloud",
    "dbaas": "base de données en tant que service cloud",
    "xaas": "tout en tant que service cloud",
    "aws": "amazon web services cloud infrastructure déploiement services cloud",
    "gcp": "google cloud platform cloud infrastructure déploiement services cloud",
    "azure": "microsoft azure cloud infrastructure déploiement services cloud",
    "oci": "oracle cloud infrastructure services cloud",
    "ibm cloud": "ibm cloud infrastructure services cloud",
    "ovh": "cloud ovh infrastructure hébergement services cloud",
    "vpc": "réseau privé virtuel cloud isolation réseau",
    "subnet": "sous réseau segmentation réseau cloud",
    "lb": "équilibrage de charge répartition trafic",
    "elb": "équilibrage de charge élastique répartition trafic",
    "cdn": "réseau diffusion contenu performance web",
    "waf": "pare feu applicatif web sécurité",
    "nat": "traduction adresse réseau connectivité",
    "igw": "passerelle internet réseau cloud",
    "sg": "groupe de sécurité filtrage réseau cloud",
    "iam": "gestion identités accès sécurité autorisations",
    "kms": "gestion des clés chiffrement sécurité",
    "hsm": "module matériel sécurité chiffrement",
    "s3": "stockage objet cloud",
    "ec2": "machine virtuelle cloud calcul",
    "rds": "base de données relationnelle managée cloud",
    "eks": "kubernetes managé cloud",
    "gke": "kubernetes managé google cloud",
    "aks": "kubernetes managé azure",
    "lambda": "fonction serverless cloud exécution événementielle",
    "cloud run": "exécution conteneurs serverless cloud",
    "bigquery": "entrepôt de données analytique cloud",
    "pubsub": "messagerie publication abonnement cloud",
    "dataproc": "traitement big data managé spark hadoop",
    "glue": "intégration de données managée cloud",
    "athena": "requêtage sql sur stockage objet",
    "redshift": "entrepôt de données analytique cloud",
    "snowflake": "plateforme données cloud analytique",
    "databricks": "plateforme ingénierie données analytique apprentissage automatique",
    "synapse": "plateforme analytique cloud intégrée",

    # =========================================================
    # CONTENEURS / ORCHESTRATION
    # =========================================================
    "ctr": "conteneur isolation applicative",
    "container": "conteneur isolation applicative",
    "containers": "conteneurs isolation applicative",
    "docker": "conteneurs déploiement applicatif isolation",
    "podman": "conteneurs exécution isolation applications",
    "k8s": "kubernetes orchestration conteneurs infrastructure déploiement cloud",
    "k3s": "kubernetes léger orchestration conteneurs",
    "eks": "kubernetes managé cloud",
    "gke": "kubernetes managé google cloud",
    "aks": "kubernetes managé azure",
    "helm": "gestion paquets kubernetes déploiement applications",
    "istio": "maillage de services observabilité sécurité trafic",
    "service mesh": "maillage de services observabilité sécurité trafic",
    "mesh": "maillage de services communication microservices",
    "pod": "unité déploiement kubernetes conteneurs",
    "svc": "service kubernetes exposition applications réseau",
    "ingress": "routage trafic entrant kubernetes",
    "egress": "trafic sortant réseau sécurité",
    "operator": "automatisation gestion applications kubernetes",
    "crd": "ressource personnalisée kubernetes extension api",
    "sidecar": "conteneur auxiliaire architecture microservices",

    # =========================================================
    # BUSINESS / SI / OUTILS D’ENTREPRISE
    # =========================================================
    "crm": "gestion relation client",
    "erp": "gestion entreprise système intégré",
    "hris": "système information ressources humaines",
    "sirh": "système information ressources humaines",
    "cms": "gestion contenu web",
    "lms": "plateforme apprentissage en ligne",
    "plm": "gestion cycle de vie produit",
    "scm": "gestion chaîne logistique supply chain management",
    "wms": "gestion entrepôt logistique",
    "tms": "gestion transport logistique",
    "mes": "système d'exécution de fabrication industrie",
    "bpm": "gestion processus métier workflows optimisation",
    "bpms": "système gestion processus métier workflows",
    "eam": "gestion des actifs d'entreprise maintenance",
    "ecm": "gestion de contenu d'entreprise documentaire",
    "cpq": "configuration tarification devis vente",
    "pos": "point de vente encaissement commerce",
    "pim": "gestion informations produit catalogue",
    "mdm": "gestion des données de référence gouvernance données",

    # =========================================================
    # IOT / EMBARQUÉ / INDUSTRIE
    # =========================================================
    "iot": "internet objets systèmes connectés",
    "iiot": "internet industriel objets",
    "m2m": "communication machine machine",
    "ot": "technologies opérationnelles systèmes industriels",
    "plc": "automate programmable industriel",
    "scada": "supervision contrôle acquisition données industrielles",
    "edge": "informatique périphérie traitement local",
    "fog": "informatique distribuée intermédiaire périphérie cloud",
    "rtos": "système d'exploitation temps réel",
    "can": "réseau bus can automobile embarqué",
    "ecu": "unité de contrôle électronique embarquée",
    "adas": "aide avancée à la conduite automobile",
    "v2x": "communication véhicule avec environnement",
    "gps": "géolocalisation satellite positionnement",

    # =========================================================
    # SÉCURITÉ / IDENTITÉ / CONFORMITÉ
    # =========================================================
    "auth": "authentification",
    "authn": "authentification vérification identité",
    "authz": "autorisation contrôle accès permissions",
    "oauth": "autorisation sécurisée oauth",
    "oidc": "authentification fédérée openid connect",
    "jwt": "jeton web json authentification",
    "mfa": "authentification multi facteur",
    "2fa": "authentification à deux facteurs",
    "sso": "authentification unique",
    "pki": "infrastructure à clés publiques certificats sécurité",
    "rbac": "contrôle accès basé rôles",
    "abac": "contrôle accès basé attributs",
    "acl": "liste contrôle accès permissions sécurité",
    "dlp": "prévention fuite données sécurité",
    "casb": "courtier sécurité accès cloud",
    "cspm": "gestion posture sécurité cloud",
    "cwpp": "protection charges de travail cloud",
    "cnapp": "plateforme protection applications cloud natives",
    "soc": "centre sécurité surveillance incidents",
    "siem": "supervision sécurité événements analyse",
    "soar": "orchestration automatisation réponse sécurité",
    "ids": "détection intrusion sécurité",
    "ips": "prévention intrusion sécurité",
    "edr": "détection réponse sur terminaux sécurité",
    "xdr": "détection réponse étendue sécurité",
    "ndr": "détection réponse réseau sécurité",
    "waf": "pare feu applicatif web sécurité",
    "av": "antivirus sécurité",
    "mssp": "prestataire sécurité managée",
    "pentest": "test d'intrusion sécurité offensive",
    "ossint": "renseignement sources ouvertes sécurité",
    "osint": "renseignement sources ouvertes sécurité",
    "cve": "vulnérabilité sécurité référencée",
    "cwe": "faiblesse sécurité logicielle",
    "owasp": "sécurité applications web bonnes pratiques",
    "gdpr": "protection données réglementation",
    "rgpd": "protection données réglementation",
    "dpo": "protection données conformité",
    "pii": "données personnelles identifiables conformité",
    "pci dss": "norme sécurité données paiement",
    "iso 27001": "management sécurité de l'information norme conformité",

    # =========================================================
    # FORMATS / ÉCHANGES DE DONNÉES / SÉRIALISATION
    # =========================================================
    "csv": "fichier données tabulaires",
    "tsv": "fichier données tabulaires séparées tabulations",
    "json": "format données json",
    "jsonl": "format json lignes données semi structurées",
    "ndjson": "json délimité par lignes données semi structurées",
    "xml": "format données xml",
    "yaml": "format données yaml",
    "yml": "format données yaml",
    "ini": "fichier configuration texte",
    "toml": "format configuration texte structuré",
    "avro": "format sérialisation données",
    "parquet": "format données colonnes big data",
    "orc": "format colonnes big data analytique",
    "proto": "protobuf sérialisation messages structurés",
    "protobuf": "sérialisation données structurées communication services",
    "msgpack": "format sérialisation binaire compact",
    "pdf": "document portable format fichier",
    "xls": "fichier tableur excel",
    "xlsx": "fichier tableur excel",
    "docx": "document texte word",
    "pptx": "présentation powerpoint",

    # =========================================================
    # SQL / REQUÊTAGE / MODÉLISATION
    # =========================================================
    "sql": "langage requête données bases de données",
    "plsql": "procédures sql programmation base de données",
    "tsql": "transact sql requêtes procédures base de données",
    "ddl": "définition structures données",
    "dml": "manipulation données",
    "dcl": "contrôle accès données",
    "tcl": "gestion transactions",
    "cte": "expression de table commune requêtes sql",
    "sp": "procédure stockée base de données",
    "sproc": "procédure stockée base de données",
    "udf": "fonction définie par utilisateur base de données",
    "join": "jointure tables relationnelles sql",
    "pk": "clé primaire identifiant unique",
    "fk": "clé étrangère relation entre tables",
    "idx": "index optimisation requêtes base de données",

    # =========================================================
    # VERSIONING / COLLABORATION / GIT
    # =========================================================
    "vcs": "gestion versions code",
    "scm": "gestion configuration logicielle gestion versions",
    "git": "gestion versions code source collaboration",
    "svn": "gestion versions centralisée code",
    "cvs": "gestion versions centralisée historique code",
    "pr": "pull request revue de code collaboration",
    "mr": "merge request revue de code collaboration",
    "repo": "dépôt code source versionné",
    "monorepo": "dépôt unique plusieurs projets",
    "trunk": "branche principale développement",
    "trunk based": "développement basé sur branche principale intégration continue",

    # =========================================================
    # TEST / QUALITÉ / VALIDATION
    # =========================================================
    "qa": "assurance qualité logiciel",
    "qc": "contrôle qualité",
    "uat": "tests validation utilisateur",
    "tdd": "développement piloté tests",
    "atdd": "développement piloté par les tests d'acceptation",
    "unit test": "test unitaire validation composants logiciels",
    "e2e": "test de bout en bout validation parcours complet",
    "e2e test": "test de bout en bout validation parcours complet",
    "it": "tests d'intégration validation interfaces composants",
    "smoke test": "test rapide de vérification initiale",
    "regression": "test de non régression qualité logicielle",
    "load test": "test de charge performance",
    "stress test": "test de stress performance robustesse",
    "perf": "performance optimisation mesure temps réponse",
    "benchmark": "évaluation comparative performance",
    "fuzzing": "test aléatoire sécurité robustesse",
    "sonar": "analyse qualité code statique",
    "sast": "analyse statique sécurité code",
    "dast": "analyse dynamique sécurité application",
    "iast": "analyse interactive sécurité application",

    # =========================================================
    # GESTION DE PROJET / PRODUIT / ORGANISATION
    # =========================================================
    "agile": "méthodes agiles gestion projet",
    "scrum": "méthode agile scrum",
    "kanban": "gestion flux travail kanban",
    "xp": "programmation extrême agile",
    "safe": "agilité à l'échelle organisation programmes",
    "lean": "amélioration continue optimisation flux valeur",
    "pmo": "gestion projet organisation",
    "pmp": "certification gestion projet",
    "po": "product owner gestion produit agile",
    "pm": "gestion de produit ou gestion de projet coordination pilotage",
    "pmo": "bureau gestion de projet gouvernance portefeuille",
    "sm": "scrum master facilitation agile",
    "okr": "objectifs résultats clés pilotage performance",
    "kpi": "indicateur clé de performance suivi performance",
    "roadmap": "feuille de route planification produit projet",
    "mvp": "produit minimum viable expérimentation produit",
    "brd": "document besoins métier",
    "frd": "document exigences fonctionnelles",
    "prd": "document exigences produit",
    "srs": "spécification exigences logicielles",
    "rfi": "demande d'information consultation",
    "rfp": "demande de proposition consultation",
    "rfq": "demande de devis consultation",
    "moa": "maîtrise ouvrage gestion projet",
    "moe": "maîtrise œuvre réalisation technique",
    "amoa": "assistance maîtrise ouvrage accompagnement projet",
    "amoe": "assistance maîtrise œuvre accompagnement technique",

    # =========================================================
    # RÉSEAUX / PROTOCOLES / WEB
    # =========================================================
    "vpn": "réseau privé virtuel sécurisé",
    "lan": "réseau local",
    "wan": "réseau étendu",
    "man": "réseau métropolitain",
    "wlan": "réseau local sans fil",
    "vlan": "réseau local virtuel segmentation réseau",
    "sdwan": "réseau étendu défini par logiciel",
    "ip": "adresse réseau ip",
    "ipv4": "protocole internet version quatre adressage réseau",
    "ipv6": "protocole internet version six adressage réseau",
    "tcp": "protocole transmission tcp",
    "udp": "protocole udp",
    "icmp": "protocole contrôle réseau",
    "dns": "résolution noms domaine",
    "dhcp": "configuration automatique réseau",
    "nat": "traduction adresse réseau connectivité",
    "http": "protocole web",
    "https": "protocole web sécurisé",
    "ftp": "transfert fichiers",
    "sftp": "transfert sécurisé fichiers",
    "smtp": "envoi courrier électronique protocole",
    "imap": "accès courrier électronique protocole",
    "pop3": "récupération courrier électronique protocole",
    "ssh": "connexion sécurisée distante",
    "telnet": "connexion distante non sécurisée",
    "tls": "sécurité transport",
    "ssl": "sécurité chiffrement",
    "ws": "websocket communication temps réel",
    "wss": "websocket sécurisé communication temps réel",
    "cdn": "réseau diffusion contenu performance web",
    "arp": "résolution adresse réseau locale",
    "bgp": "routage inter domaine internet",
    "ospf": "protocole routage interne",
    "snmp": "supervision gestion équipements réseau",
    "nfs": "partage fichiers réseau",
    "smb": "partage fichiers réseau windows",

    # =========================================================
    # CYBER / GOUVERNANCE / RISQUE
    # =========================================================
    "grc": "gouvernance risque conformité sécurité",
    "bcp": "plan continuité activité résilience",
    "drp": "plan reprise activité résilience",
    "bia": "analyse impact activité continuité",
    "ciso": "responsable sécurité des systèmes d'information",
    "rssi": "responsable sécurité des systèmes d'information",
    "iso": "responsable sécurité information ou norme internationale",
    "pra": "plan reprise activité",

    # =========================================================
    # HPC / CALCUL SCIENTIFIQUE
    # =========================================================
    "hpc": "calcul haute performance parallèle",
    "mpi": "communication parallèle processus",
    "cuda": "calcul parallèle gpu nvidia",
    "opencl": "calcul parallèle hétérogène",
    "openmp": "parallélisme mémoire partagée",
    "slurm": "ordonnancement jobs calcul haute performance",
    "pbs": "ordonnancement jobs calcul haute performance",
    "job scheduler": "ordonnancement tâches calcul haute performance",

    # =========================================================
    # OBSERVABILITÉ / SUPERVISION / LOGS
    # =========================================================
    "apm": "supervision performance applicative observabilité",
    "rpm": "supervision performance réelle utilisateur",
    "rum": "mesure expérience utilisateur réelle performance",
    "obs": "observabilité supervision métriques logs traces",
    "otel": "open telemetry observabilité traces métriques logs",
    "mttr": "temps moyen de résolution incidents",
    "mttd": "temps moyen de détection incidents",
    "mtbf": "temps moyen entre pannes fiabilité",
    "slis": "indicateurs niveau de service mesure performance",
    "logs": "journaux événements supervision diagnostic",
    "traces": "traçage distribué observabilité",
    "metrics": "métriques supervision performance",

    # =========================================================
    # OUTILS / ÉCOSYSTÈMES COURANTS
    # =========================================================
    "js": "javascript développement web",
    "ts": "typescript développement web typé",
    "py": "python programmation développement data",
    "cpp": "c plus plus programmation système orientée objet performance",
    "csharp": "c sharp développement logiciel orienté objet",
    "cs": "c sharp développement logiciel orienté objet",
    "golang": "go programmation systèmes services réseau",
    "rb": "ruby développement web scripting",
    "sh": "script shell automatisation système",
    "bash": "script shell automatisation système",
    "ps": "powershell automatisation système windows",
    "ps1": "powershell script automatisation système windows",
    "jvm": "machine virtuelle java exécution applications",
    "jre": "environnement exécution java",
    "jdk": "kit développement java",
    "ide": "environnement développement intégré",
    "lsp": "protocole serveur de langage assistance code",

    # =========================================================
    # MÉTHODES / DOCUMENTATION / UML
    # =========================================================
    "uml": "modélisation unifiée diagrammes conception logicielle",
    "bpmn": "modélisation processus métier workflows",
    "merise": "méthode analyse conception systèmes d'information",
    "mer": "modèle entité relation modélisation données",
    "mcd": "modèle conceptuel de données",
    "mld": "modèle logique de données",
    "mpd": "modèle physique de données",
    "doc": "documentation projet technique fonctionnelle",
    "kb": "base de connaissances documentation support",

    # =========================================================
    # ABRÉVIATIONS GÉNÉRALES DÉVELOPPEMENT / PRODUIT
    # =========================================================
    "poc": "preuve de concept expérimentation faisabilité",
    "proto": "prototype maquette validation concept",
    "mvp": "produit minimum viable expérimentation produit",
    "ga": "disponibilité générale mise en production",
    "rc": "version candidate publication logicielle",
    "lts": "support à long terme version stable",
    "eol": "fin de vie produit logiciel",
    "eos": "fin de support produit logiciel",

    # =========================================================
    # ABRÉVIATIONS SPÉCIFIQUES DATA / MATHS / STATS
    # =========================================================
    "pca": "analyse en composantes principales réduction dimension",
    "tsne": "réduction dimension visualisation non linéaire",
    "umap": "réduction dimension apprentissage de variété",
    "mae": "erreur absolue moyenne évaluation régression",
    "mse": "erreur quadratique moyenne évaluation régression",
    "rmse": "racine erreur quadratique moyenne évaluation régression",
    "r2": "coefficient de détermination évaluation régression",
    "auc": "aire sous la courbe évaluation classification",
    "roc": "courbe taux vrais positifs faux positifs classification",
    "pr": "courbe précision rappel classification",
    "cv split": "validation croisée découpage données",
    "kfold": "validation croisée k plis",
    "ohe": "encodage one hot variables catégorielles",
    "tfidf": "pondération fréquence terme fréquence inverse document",
    "bow": "sac de mots représentation texte",
    "ner": "reconnaissance entités nommées traitement langage",
    "pos tagging": "étiquetage morphosyntaxique traitement langage",

    # =========================================================
    # ABRÉVIATIONS COLLAB / BUREAUTIQUE / ENTREPRISE
    # =========================================================
    "ppt": "présentation powerpoint support de présentation",
    "xls": "fichier tableur excel",
    "xlsx": "fichier tableur excel",
    "docx": "document texte word",
    "csv file": "fichier données tabulaires",
    "xlsm": "fichier excel macros",
    "vba": "visual basic pour applications automatisation bureautique",
    "erp app": "gestion entreprise système intégré",
    "crm app": "gestion relation client",

    # =========================================================
    # TOOLS
    # =========================================================

    # =========================================================
    # LANGAGES / RUNTIME / DÉVELOPPEMENT
    # =========================================================,
    "javascript": "langage programmation web front end back end",
    "typescript": "langage programmation web typé front end back end",
    "c++": "langage programmation orientée objet système performance",
    "c#": "langage programmation orientée objet développement logiciel applications .net",
    "go": "langage programmation systèmes services réseau concurrence",
    "rust": "langage programmation système sécurité mémoire performance",
    "php": "langage programmation web backend serveur",
    "scala": "langage programmation fonctionnelle big data spark",
    "kotlin": "langage programmation applications android backend",
    "swift": "langage programmation applications ios",
    "r": "langage statistique analyse données visualisation modélisation",
    "matlab": "calcul scientifique modélisation analyse numérique",
    "perl": "scripting automatisation traitement texte",
    "jupyter": "notebook interactif analyse données expérimentation",
    "jupyter notebook": "notebook interactif analyse données expérimentation",
    ".net": "plateforme développement logiciel applications entreprise",
    "dotnet": "plateforme développement logiciel applications entreprise",

    # =========================================================
    # DATA / ANALYSE / BI / SCIENTIFIC STACK
    # =========================================================
    "pandas": "bibliothèque python manipulation données analyse données traitement données dataframe",
    "numpy": "calcul numérique tableaux scientifiques python traitement données",
    "scipy": "calcul scientifique optimisation statistiques python",
    "matplotlib": "visualisation données graphiques python",
    "seaborn": "visualisation statistique données python graphiques",
    "plotly": "visualisation interactive données tableaux de bord graphiques",
    "bokeh": "visualisation interactive données python",
    "altair": "visualisation déclarative données graphiques",
    "polars": "manipulation données dataframe haute performance",
    "dask": "traitement parallèle données python big data",
    "vaex": "analyse dataframe volumineux haute performance",
    "openpyxl": "traitement fichiers excel automatisation python",
    "xlwings": "automatisation excel python",
    "pyarrow": "format colonne parquet flèches données analytique",
    "pyspark": "traitement distribué données spark python big data",
    "power bi": "informatique décisionnelle visualisation données tableaux de bord reporting aide à la décision",
    "powerbi": "informatique décisionnelle visualisation données tableaux de bord reporting aide à la décision",
    "tableau": "informatique décisionnelle visualisation données tableaux de bord reporting",
    "qlik": "informatique décisionnelle visualisation données reporting",
    "qlik sense": "informatique décisionnelle visualisation données tableaux de bord",
    "looker": "informatique décisionnelle visualisation données tableaux de bord analyse",
    "looker studio": "visualisation données reporting tableaux de bord",
    "excel": "tableur analyse données reporting calculs tableaux automatisation bureautique",
    "google sheets": "tableur collaboratif analyse données reporting",
    "sheets": "tableur collaboratif analyse données reporting",
    "sas": "analyse statistique traitement données décisionnel",
    "spss": "analyse statistique traitement données",
    "stata": "analyse statistique économétrie données",
    "minitab": "analyse statistique contrôle qualité",
    "anaconda": "environnement python data science gestion paquets",
    "conda": "gestion environnement paquets python data science",

    # =========================================================
    # MACHINE LEARNING / IA TOOLS
    # =========================================================
    "scikit-learn": "apprentissage automatique classification régression clustering python",
    "sklearn": "apprentissage automatique classification régression clustering python",
    "tensorflow": "apprentissage profond réseaux de neurones intelligence artificielle",
    "keras": "apprentissage profond réseaux de neurones tensorflow",
    "pytorch": "apprentissage profond réseaux de neurones intelligence artificielle",
    "xgboost": "gradient boosting apprentissage automatique prédiction",
    "lightgbm": "gradient boosting apprentissage automatique prédiction",
    "catboost": "gradient boosting variables catégorielles apprentissage automatique",
    "opencv": "vision par ordinateur traitement image",
    "hugging face": "modèles de langage traitement du langage naturel apprentissage profond",
    "huggingface": "modèles de langage traitement du langage naturel apprentissage profond",
    "transformers": "modèles transformeurs traitement du langage naturel vision",
    "langchain": "orchestration applications llm agents rag",
    "llamaindex": "indexation données rag applications llm",
    "mlflow": "suivi expériences apprentissage automatique gestion modèles",
    "wandb": "suivi expériences apprentissage automatique visualisation",
    "weights & biases": "suivi expériences apprentissage automatique visualisation",

    # =========================================================
    # BIG DATA / STREAMING / ORCHESTRATION
    # =========================================================
    "spark": "traitement distribué big data calcul distribué analytique",
    "hadoop": "stockage distribué traitement distribué big data",
    "hdfs": "système fichiers distribué big data",
    "hive": "entrepôt de données sql big data",
    "impala": "requêtage sql big data analytique",
    "presto": "moteur sql distribué requêtage analytique",
    "trino": "moteur sql distribué requêtage analytique",
    "airflow": "orchestration pipelines workflows données",
    "dagster": "orchestration pipelines données workflows",
    "luigi": "orchestration pipelines traitement données",
    "nifi": "flux données ingestion transformation",
    "kafka": "streaming événements messagerie distribuée",
    "kinesis": "streaming données temps réel cloud",
    "flink": "traitement flux données temps réel distribué",
    "beam": "traitement unifié batch streaming données",
    "dbt": "transformation données analytique sql modélisation",
    "debezium": "capture changements données cdc streaming",

    # =========================================================
    # BASES DE DONNÉES / STOCKAGE
    # =========================================================
    "postgresql": "base de données relationnelle sql analytique transactionnelle",
    "postgres": "base de données relationnelle sql analytique transactionnelle",
    "mysql": "base de données relationnelle sql",
    "mariadb": "base de données relationnelle sql",
    "sqlite": "base de données relationnelle légère embarquée",
    "oracle": "base de données relationnelle entreprise sql",
    "sql server": "base de données relationnelle microsoft sql",
    "mssql": "base de données relationnelle microsoft sql",
    "mongodb": "base de données documentaire nosql",
    "mongo": "base de données documentaire nosql",
    "cassandra": "base de données distribuée nosql haute disponibilité",
    "redis": "base de données clé valeur cache mémoire",
    "elasticsearch": "moteur recherche indexation analyse logs texte",
    "elastic": "moteur recherche indexation analyse logs texte",
    "neo4j": "base de données graphe relations données",
    "influxdb": "base de données séries temporelles",
    "timescaledb": "base de données séries temporelles postgresql",
    "duckdb": "base de données analytique locale colonnaire sql",
    "clickhouse": "base de données analytique colonnaire haute performance",
    "couchbase": "base de données documentaire nosql distribuée",
    "dynamodb": "base de données clé valeur document cloud",
    "firebase": "base de données temps réel backend cloud mobile",
    "supabase": "backend base de données postgresql authentification api",
    "superset": "visualisation données tableaux de bord open source",

    # =========================================================
    # DEVOPS / INFRA / AUTOMATISATION / CLOUD TOOLS
    # =========================================================
    "ansible": "automatisation configuration déploiement infrastructure",
    "terraform": "infrastructure en tant que code provisionnement cloud",
    "packer": "construction images machines automatisation infrastructure",
    "vagrant": "environnements virtuels développement automatisation",
    "jenkins": "intégration continue automatisation build tests déploiement",
    "gitlab ci": "intégration continue déploiement continu gitlab",
    "github actions": "intégration continue automatisation workflows github",
    "circleci": "intégration continue automatisation pipelines",
    "travis ci": "intégration continue automatisation tests",
    "argo cd": "déploiement continu gitops kubernetes",
    "argocd": "déploiement continu gitops kubernetes",
    "prometheus": "supervision métriques observabilité systèmes",
    "grafana": "visualisation métriques supervision observabilité tableaux de bord",
    "kibana": "visualisation logs observabilité analyse",
    "logstash": "collecte transformation logs",
    "filebeat": "collecte logs supervision observabilité",
    "metricbeat": "collecte métriques supervision observabilité",
    "portainer": "gestion conteneurs docker kubernetes interface",
    "nginx": "serveur web proxy inverse répartition charge",
    "apache": "serveur web hébergement applications",
    "apache http server": "serveur web hébergement applications",
    "traefik": "proxy inverse routage conteneurs",
    "rabbitmq": "messagerie file messages systèmes distribués",
    "activemq": "messagerie file messages intégration systèmes",
    "zookeeper": "coordination systèmes distribués",
    "consul": "découverte services configuration distribuée",
    "vault": "gestion secrets sécurité accès",
    "minio": "stockage objet compatible s3",
    "openshift": "plateforme conteneurs kubernetes entreprise",
    "helm chart": "paquet kubernetes déploiement application",
    "linux": "système exploitation administration serveurs développement",
    "ubuntu": "système exploitation linux",
    "debian": "système exploitation linux",
    "centos": "système exploitation linux entreprise",
    "red hat": "linux entreprise administration systèmes",
    "rhel": "linux entreprise administration systèmes",
    "unix": "système exploitation multiutilisateur",
    "wsl": "sous système windows pour linux développement",
    "virtualbox": "virtualisation machines virtuelles",
    "proxmox": "virtualisation infrastructure serveurs",
    "cloudbuild": "intégration continue build cloud",
    "artifact registry": "registre artefacts conteneurs paquets",
    "ecr": "registre conteneurs cloud",
    "acr": "registre conteneurs azure",
    "gcr": "registre conteneurs google cloud",

    # =========================================================
    # FRAMEWORKS WEB / API / APP
    # =========================================================
    "fastapi": "framework api python web backend",
    "flask": "framework web python api backend léger",
    "django": "framework web python backend orm applications",
    "spring": "framework java backend applications entreprise",
    "spring boot": "framework java microservices api backend",
    "node.js": "runtime javascript backend services web",
    "nodejs": "runtime javascript backend services web",
    "express": "framework web node javascript api backend",
    "nestjs": "framework node typescript backend api architecture",
    "react": "bibliothèque interface utilisateur front end web",
    "next.js": "framework react rendu serveur applications web",
    "nextjs": "framework react rendu serveur applications web",
    "vue": "framework interface utilisateur front end web",
    "angular": "framework front end web typescript",
    "svelte": "framework front end web interface utilisateur",
    "streamlit": "applications data interactives python visualisation",
    "gradio": "interfaces interactives machine learning python",
    "tkinter": "interface graphique python bureau",
    "flutter": "framework applications mobiles multiplateformes",
    "react native": "développement mobile multiplateforme react",
    "android studio": "développement applications android ide",

    # =========================================================
    # VERSIONING / COLLAB / PRODUCTIVITY TOOLS
    # =========================================================
    "github": "gestion code source versioning collaboration dépôt git",
    "gitlab": "gestion code source versioning ci cd collaboration",
    "bitbucket": "gestion code source versioning collaboration",
    "jira": "gestion projet agile tickets suivi travail",
    "confluence": "documentation collaborative base connaissances",
    "notion": "documentation organisation collaboration",
    "trello": "gestion projet kanban collaboration",
    "figma": "conception interface utilisateur prototypage design collaboratif",
    "miro": "collaboration visuelle tableaux blancs ateliers",
    "postman": "test api requêtes documentation",
    "insomnia": "test api requêtes",
    "swagger": "documentation api openapi",
    "openapi": "spécification interfaces api documentation",
    "selenium": "automatisation tests web",
    "cypress": "tests end to end applications web",
    "playwright": "tests automatisés web end to end",

    # =========================================================
    # CLOUD ABBRÉVIATIONS UTILES EN PLUS
    # =========================================================
    "gcs": "google cloud storage stockage objet cloud",
    "bq": "bigquery entrepôt de données analytique cloud",
    "gke autopilot": "kubernetes managé automatisé google cloud",
    "vm instance": "machine virtuelle cloud calcul",
    "vm instances": "machines virtuelles cloud calcul",
    "cf": "cloud functions serverless fonctions cloud",
    "gcf": "google cloud functions serverless",
    "run svc": "service cloud run conteneur serverless",
}


def preprocess_it_text(text: str) -> str:
    if not isinstance(text, str) or not text.strip():
        return ""

    text_clean = text.lower().strip()

    for abbr in sorted(IT_MAPPING.keys(), key=len, reverse=True):
        expansion = IT_MAPPING[abbr]
        pattern = r"\b" + re.escape(abbr) + r"\b"
        text_clean = re.sub(pattern, f"{abbr} {expansion}", text_clean)

    text_clean = re.sub(r"\s+", " ", text_clean).strip()
    return text_clean


if __name__ == "__main__":

    test_str = """Projet d'analyse de données Netflix :
    nettoyage dataset (data cleaning, gestion des NA, normalisation)
    EDA + visualisation (matplotlib, seaborn)
    création dashboard Power BI
    analyse des tendances (genres, pays, ratings)
    restitution insights business
    Projet data engineering léger :
    ingestion données CSV → PostgreSQL
    transformation (pandas)
    structuration tables (data modeling)
    automatisation scripts
    Résultats : amélioration lisibilité des données + aide à la prise de décision via KPI.
    """
    print("Original :", test_str)
    print("Nettoyé  :", preprocess_it_text(test_str))